### PR TITLE
Update Test-MgCommandPrerequisites.ps1

### PR DESCRIPTION
**Pull request by BohrenAn**
Find-MgGraphCommand with API Version "beta" does not return anything. Therefore the Test-MgCommandPrerequisites Fails

Fixes #

### Changes proposed in this pull request

-
-
-

### Documentation

- [ ] All exported commands have Synopsis, Parameter Descriptions, and at least one Example.

### Other links

-
-
-

### CODE REVIEW

**Comment by BohrenAn** [comment]
Created Issue in msgraph-sdk-powershell
https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2582

The Parameter -APIVersion should not be used since Microsoft.Graph 2.x anymore. It's a leftover from 1.x

Regards
Andres

**Comment by BohrenAn** [comment]
@merill Can someone please review this Pull request?

**Review by merill — APPROVED** [review]

**Review by merill — APPROVED** [review]

**Comment by merill** [comment]
Thanks a lot for the PR @BohrenAn, sorry it took so long. Tx!

**Comment by SuryenduB** [comment]
This Merge is introducing new bug for the command `Get-MsIdCrossTenantAccessActivity` 

```
GROUP\Documents\PowerShell\Modules\Microsoft.Graph.Authentication\2.23.0\custom\Find-MgGraphCommand.ps1:194 char:29
+ …             Write-Error "'$c' is not a valid Microsoft Graph PowerShe …
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by SuryenduB** [comment]
@merill @BohrenAn , can you please check this ?

**Comment by robbieveivers** [comment]
image
image
Yeah i'd agree, we need to make sure this can work for both v1 and Beta command Searches. 

Lucky only two commands are using Beta commands (Get-MsIdCrossTenantAccessActivity.ps, ConvertFrom-MsIdUniqueTokenIdentifier.ps1), hence why this bug has been not found. 
image

Ill create a separate issue to work on this

**Comment by robbieveivers** [comment]
Working off Issue #70 
Test-MgCommandPrerequisites Must be able to handle v1 and beta via the APIVersion Parameter again

**Pull request merged**
