### PR TITLE
Updating Export-MsIdAppConsentGrantReport, Fix Test-MgCommandPrerequisites, Update Styling of Example to Pass Main Test

### LINKED ISSUE #41: The term 'Get-MgServicePrincipalCount' is not recognized as the name of a cmdlet,"
### Describe the bug

Hi,

I just ran this for the first time, running the latest version of MSIdentityTools.

Am I missing a dependency?

Running on Windows 10 with PS version 5.1

PS C:\temp> Install-Module -Name MSIdentityTools                                                                                                                                                 PS C:\temp> Install-Module -Name ImportExcel                                                                                                                                                     PS C:\temp> Connect-MgGraph -Scopes Application.Read.All                                                                                                                                         Welcome to Microsoft Graph!  

....

PS C:\temp> Export-MsIdAppConsentGrantReport -ReportOutputType ExcelWorkbook -ExcelWorkbookPath .\appaccess.xlsx

 Get-MgServicePrincipalCount : The term 'Get-MgServicePrincipalCount' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or   if a path was included, verify that the path is correct and try again.                                                                                                                           At C:\Program Files\WindowsPowerShell\Modules\MSIdentityTools\2.0.52\MSIdentityTools.psm1:2900 char:18
+         $count = Get-MgServicePrincipalCount -ConsistencyLevel eventu ...
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-MgServicePrincipalCount:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Get-MgServicePrincipal : The term 'Get-MgServicePrincipal' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path
was included, verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\MSIdentityTools\2.0.52\MSIdentityTools.psm1:2904 char:37
+         $script:ServicePrincipals = Get-MgServicePrincipal -ExpandPro ...
+                                     ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-MgServicePrincipal:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

The variable '$script:ServicePrincipals' cannot be retrieved because it has not been set.
At C:\Program Files\WindowsPowerShell\Modules\MSIdentityTools\2.0.52\MSIdentityTools.psm1:2971 char:29
+         foreach ($client in $script:ServicePrincipals) {
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (script:ServicePrincipals:String) [], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined

The variable '$script:servicePrincipals' cannot be retrieved because it has not been set.
At C:\Program Files\WindowsPowerShell\Modules\MSIdentityTools\2.0.52\MSIdentityTools.psm1:3013 char:30
+         $servicePrincipals = $script:servicePrincipals
+                              ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (script:servicePrincipals:String) [], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined

The variable '$script:servicePrincipals' cannot be retrieved because it has not been set.
At C:\Program Files\WindowsPowerShell\Modules\MSIdentityTools\2.0.52\MSIdentityTools.psm1:3021 char:16
+         $job = $script:servicePrincipals | ForEach-Object -AsJob -Thr ...
+                ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (script:servicePrincipals:String) [], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined

The property 'State' cannot be found on this object. Verify that the property exists.
At C:\Program Files\WindowsPowerShell\Modules\MSIdentityTools\2.0.52\MSIdentityTools.psm1:3042 char:16
+         while ($job.State -eq 'Running') {
+                ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

An error occurred while retrieving app consent grants. Please try again.
At C:\Program Files\WindowsPowerShell\Modules\MSIdentityTools\2.0.52\MSIdentityTools.psm1:2891 char:13
+             throw "An error occurred while retrieving app consent gra ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (An error occurr...ease try again.:String) [], RuntimeException
    + FullyQualifiedErrorId : An error occurred while retrieving app consent grants. Please try again.

### LINKED ISSUE #46: Error after running Export-MsIdAppConsentGrantReport
I've been following the steps from the youtube video: 

https://www.youtube.com/watch?v=vO0m5yE3dZA

At the step running Export-MsIdAppConsentGrantReport I see a slew of the following error message:

PropertyNotFoundException: The property 'AdditionalProperties' cannot be found on this object. Verify that the property exists.

My powershell details are:

PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Looking at the generated xlsx I can see what appears to be all of the details I'd expect, but I wouldn't know what the above error message has prevented from appearing in the report.

### PR DESCRIPTION
**Pull request by robbieveivers**
Fixes #41 - Error after running Export-MsIdAppConsentGrantReport - Microsoft.Graph.Applications not installed
Fixes #46 - The term 'Get-MgServicePrincipalCount' is not recognized as the name of a cmdlet," , Microsoft.Graph.DirectoryObject not installed
Both are checked to see if they have prerequisites installed.
image

### Changes proposed in this pull request

- Update Export-MsIdAppConsentGrantReport to use existing Test-MgCommandPrerequisites to check modules are installed
- Fix Test-MgCommandPrerequisites as it could not handle if Find-MgGraphCommand returned a single command.
- Updated Styling of Examples in some functions so the Main Pester Test was happy, e.g Copyright year 2024, some examples missing descriptions.

### Testing

Pester
Added Find-MgGraphCommand: Returns Single Command to Test-MgCommandPrerequisites.tests.ps1

Manual
Tested when a module is missing. Error suggests for the user to install the missing module with the correct version.
image

### Documentation

No New Commands, extra code self documenting comments where required.
- [x] All exported commands have Synopsis, Parameter Descriptions, and at least one Example.

### CODE REVIEW

**Comment by robbieveivers** [comment]
@microsoft-github-policy-service agree

**Comment by robbieveivers** [comment]
Added Extra Verbose error messages to Troubleshoot further issues and makes it clear your missing modules which are required or if other issues occur when calling graph commands. We shouldn't see these errors anymore as we are using the common check Test-MgCommandPrerequisites anyway.
Fixes #44 - Export-MsIdAppConsentGrantReport

**Review by merill — APPROVED** [review]
Thanks a lot @robbieveivers this is a fantastic PR! Much appreciated.

Will be included in the next update.

**Review by merill — APPROVED** [review]
Thanks a lot @robbieveivers this is a fantastic PR! Much appreciated.

Will be included in the next update.

**Pull request merged**
